#!/bin/bash
SCRIPT_DIR=$(dirname "$(realpath "$0")")

BUILD_SKIP="N"
BOX_CMD=""
BOX_NAME=""

while [[ "${#}" -gt 0 ]]; do
    case "${1}" in
        --skip-build)
            BUILD_SKIP="Y"
            shift 1
            ;;
        *)            
            BOX_NAME="${1}"
            shift

            BOX_CMD="${@}"
            break
    esac
done

BOX_IMAGE="localhost/${BOX_NAME}-box:latest"

if [ "${BUILD_SKIP}" == "N" ]; then
    podman image exists ${BOX_IMAGE}
    if [ "$?" != "0" ]; then
        ${SCRIPT_DIR}/tb-build ${BOX_NAME}
    fi
fi

podman container exists ${BOX_NAME}-box
if [ "$?" != "0" ]; then
    toolbox create --image ${BOX_IMAGE} ${BOX_NAME}-box
else
    is_running="$(podman inspect ${BOX_NAME}-box --format '{{ .State.Running }}')"
    if [ "${is_running}" == "false" ]; then
      podman start ${BOX_NAME}-box
    fi
fi
